name: automated-testing-api

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main","staging", "feature/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Clean install with maven
        run: mvn clean install

      - name: Execution test Get
        run: mvn test -Dtest=apis.GetProductsTest

      - name: Execution test Post
        run: mvn test -Dtest=apis.PostAddProductTest
        
      - name: Execution test Put
        run: mvn test -Dtest=apis.PutUpdateProductTest

      - name: Execution test Delete
        run: mvn test -Dtest=apis.DeleteProductTest

      - name: Generate reports apis
        uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: api-test-report
          path: sparkreporter
          
      - name: Merge any -> staging
        if: startsWith(github.ref, 'refs/heads/feature/')  # Check if the branch is a feature branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: staging
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete merged feature branch
        if: startsWith(github.ref, 'refs/heads/feature/')  # Check if the branch is a feature branch
        run: |
          git push origin --delete ${{ github.ref }}
        
      # Optional: Clean up tags if required
      - name: Clean up local tags
        run: |
          git fetch --tags
